# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: aws-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# How do we want it?
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ssd
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
  encrypted: "true"


# ---
# # How do we want it implemented
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-storage
# spec:
#   storageClassName: aws-ssd
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/tmp/storage"
#     type: DirectoryOrCreate